### ISSUE TITLE
Pre-Launch checklist

### ISSUE THREAD

**Issue by roberthamel** [roberthamel/microstrain-static#1]
**Front Page**
- [x] find pages to convert
- [x] collect images
- [x] consolidate css
- [x] consolidate js
- [x] change links to hash

**Comment by roberthamel** [comment]
**inertial/nodes **
- [ ] find pages to convert
- [ ] collect images
- [ ] change links to hash
- [ ] consolidate css
- [ ] consolidate js

**Comment by roberthamel** [comment]
**inertial/nodes/3DM-GX5-45 **
- [ ] find pages to convert
- [ ] collect images
- [ ] change links to hash
- [ ] consolidate css
- [ ] consolidate js

**Comment by roberthamel** [comment]
**parameters/acceleration**
- [ ] find pages to convert
- [ ] collect images
- [ ] change links to hash
- [ ] consolidate css
- [ ] consolidate js

**Comment by roberthamel** [comment]
**support/news**
- [ ] find pages to convert
- [ ] collect images
- [ ] change links to hash
- [ ] consolidate css
- [ ] consolidate js
